package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.3
 * 2012-11-13T17:02:23.906+09:00
 * Generated source version: 2.5.3
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "Receive360ResultSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface Receive360ResultSoap {

    /**
     * BT360으로부터 WM오더 수신 처리(VS2)
     */
    @WebResult(name = "Receive360WorkOrderResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Receive360WorkOrder", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Receive360WorkOrder")
    @WebMethod(operationName = "Receive360WorkOrder", action = "http://tempuri.org/Receive360WorkOrder")
    @ResponseWrapper(localName = "Receive360WorkOrderResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Receive360WorkOrderResponse")
    public org.tempuri.Receive360WorkOrderResult receive360WorkOrder(
        @WebParam(name = "WorkOrder", targetNamespace = "http://tempuri.org/")
        org.tempuri.ArrayOfReceive360WorkOrderInputParam workOrder
    );

    /**
     * BT360으로부터 WM오더 수동스케줄링 수신 처리(VS7)
     */
    @WebResult(name = "receive360ManualAllocationResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "receive360ManualAllocation", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Receive360ManualAllocation")
    @WebMethod(action = "http://tempuri.org/receive360ManualAllocation")
    @ResponseWrapper(localName = "receive360ManualAllocationResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Receive360ManualAllocationResponse")
    public org.tempuri.Receive360WorkOrderResult receive360ManualAllocation(
        @WebParam(name = "WorkOrder", targetNamespace = "http://tempuri.org/")
        org.tempuri.ArrayOfReceive360ManualAllocationInputParam workOrder
    );
}
