//created on: 2012. 10. 15
package com.kt.oss.wmIntgl.datamapper.service.rules.mapper

import com.kt.oss.wmIntgl.common.constants.ScenarioType;
import com.kt.oss.wmIntgl.common.utils.ConversionUtil;
import com.kt.oss.wmIntgl.datahandler.domain.IntglDataVo;
import com.kt.oss.wmIntgl.datahandler.domain.WMAppointmentOrder;
import com.kt.oss.wmIntgl.datahandler.domain.WMAvailabilityPattern;
import com._360scheduling.schema.dsscheduledata.DsScheduleData.AvailabilityPattern;

// vstype == 6 이면
// id : [appointmentRequestId] + '_' + [slotId] 매핑
// period_start_datetime : [periodStartDt] 매핑
// period_end_datetime : [periodEndDt] 매핑
// day_pattern : [dayPattern] 매핑
// open_time : [openTime] 매핑
// close_time : [closeTime] 매핑
// time_zone : default '' 설정
// activity_id : [appointmentRequestId] 매핑
// start_based : Default 값으로 true 설정
// appointment_request_id : [appointmentRequestId] 매핑
rule "VS6_AvailabilityPattern"
	dialect "java"
	no-loop
	when
		pattern : WMAvailabilityPattern()
		intglVo : IntglDataVo(vsType == ScenarioType.VS6)
		availabilityPattern : AvailabilityPattern()
	then
		availabilityPattern.setId(intglVo.getAppointmentRequestId() + "_" + pattern.getSlotId());
		availabilityPattern.setPeriodStartDatetime(pattern.getPeriodStartDt());
		availabilityPattern.setPeriodEndDatetime(pattern.getPeriodEndDt());
		availabilityPattern.setDayPattern(pattern.getDayPattern());
		availabilityPattern.setOpenTime(ConversionUtil.getIntToDuration(true, 0, Integer.parseInt(pattern.getOpenTime().split(":")[0]), Integer.parseInt(pattern.getOpenTime().split(":")[1]), 0));
		availabilityPattern.setCloseTime(ConversionUtil.getIntToDuration(true, 0, Integer.parseInt(pattern.getCloseTime().split(":")[0]), Integer.parseInt(pattern.getCloseTime().split(":")[1]), 0));
		availabilityPattern.setTimeZone("");
		availabilityPattern.setActivityId(intglVo.getAppointmentRequestId());
		availabilityPattern.setStartBased(true);
		availabilityPattern.setAppointmentRequestId(intglVo.getAppointmentRequestId());
        update(availabilityPattern);
end
