//created on: 2012. 10. 15
package com.kt.oss.wmIntgl.datamapper.service.rules.mapper

import com.kt.oss.wmIntgl.common.constants.ScenarioType;
import com.kt.oss.wmIntgl.datahandler.domain.WMDivisionInfo;
import com.kt.oss.wmIntgl.datahandler.domain.IntglDataVo;
import com.kt.oss.wmIntgl.datamapper.service.rules.core.RulesVo;
import com._360scheduling.schema.dsmodelling.DsModelling.RAMDivision;

// vstype == 16 이면
// id : [officeScode] + "_" + [workTeamCode]
// description : [officeName] + " " + [workTeamCode] + "조"
// send : Default 값으로 true 설정
// ram_division_id : [officeScode] 매핑
// ram_division_type_id : Default 값으로 'pwa' 설정
rule "VS16_RAMDivision"
	dialect "java"
	no-loop
	when
		order : WMDivisionInfo()
		intglVo : IntglDataVo(vsType == ScenarioType.VS16)
		rulesVo : RulesVo()
		ramDivision : RAMDivision()
	then
		ramDivision.setId(order.getOfficeScode() + "_" + order.getWorkTeamCode());
		ramDivision.setDescription(order.getOfficeName() + " " + order.getWorkTeamCode() + rulesVo.getPostfix());
		ramDivision.setSend(true);
		ramDivision.setRamDivisionId(order.getOfficeScode());
		ramDivision.setRamDivisionTypeId("pwa");
        update(ramDivision);
end
