//created on: 2012. 10. 15
package com.kt.oss.wmIntgl.datamapper.service.rules.mapper

import com.kt.oss.wmIntgl.common.constants.ScenarioType;
import com.kt.oss.wmIntgl.common.utils.StringUtil;
import com.kt.oss.wmIntgl.datahandler.domain.IntglDataVo;
import com.kt.oss.wmIntgl.datahandler.domain.WMResourceHolidayInfo;
import com._360scheduling.schema.dsmodelling.DsModelling.RAMUnavailability;

// vstype == 14C 이면..
// id : [workerId] + "_" + [eventDate] 매핑 ex) 91002532_20121229
// ram_resource_id : [workerId] 매핑
// ram_time_pattern_id : [workerId] + "_" + [eventDate]매핑 ex) 91002532_20121229
// ram_unavailability_category_id : HolidayTcode를 인자로 TB_WM_MAPPINGTPROG 테이블에서 TPROG를 조회하여 매핑 == [HolidayTcode] 매핑
rule "VS14C_RAMUnavailability"
	dialect "java"
	no-loop
	when
		order : WMResourceHolidayInfo()
		intglVo : IntglDataVo(vsType == ScenarioType.VS14C)
		ramUnavailability : RAMUnavailability()
	then
		ramUnavailability.setId(order.getWorkerId() + "_" + order.getEventDate());
		ramUnavailability.setRamResourceId(order.getWorkerId());
		ramUnavailability.setRamTimePatternId(order.getWorkerId() + "_" + order.getEventDate());
		ramUnavailability.setRamUnavailabilityCategoryId(order.getHolidayTcode());
        update(ramUnavailability);
end
