//created on: 2012. 10. 15
package com.kt.oss.wmIntgl.datamapper.service.rules.mapper

import com.kt.oss.wmIntgl.common.constants.ScenarioType;
import com.kt.oss.wmIntgl.common.utils.StringUtil;
import com.kt.oss.wmIntgl.datahandler.domain.IntglDataVo;
import com.kt.oss.wmIntgl.datahandler.domain.WMAppointmentOrder;
import com.kt.oss.wmIntgl.datahandler.domain.WMWorkOrder;
import com._360scheduling.schema.dsscheduledata.DsScheduleData.ResourcePreference;

// vstype == 1 이면..
// Id : "RP_" + activity_id 매핑 또는 UUID 설정 [bt360ExpWorkerId]를 체크하여 값이 없을 경우 Resouce_Preference 생성 안함.
// resource_id : [bt360ExpWorkerId] 매핑
// activity_id (or activity_Type_id or location_id) : [worktype] + [officeScode] + [workOdrNum ] 매핑
// preference : [bt360Preference] 매핑
rule "VS1_ResourcePreference"
	dialect "java"
	no-loop
	when
		order : WMWorkOrder()
		intglVo : IntglDataVo(vsType == ScenarioType.VS1)
		resourcePreference : ResourcePreference()
	then
		resourcePreference.setId(StringUtil.getUUID());
		resourcePreference.setResourceId(order.getBt360ExpWorkerId());
		resourcePreference.setActivityId(order.getWorkType() + order.getOfficeScode() + order.getWorkOdrNum());
		resourcePreference.setPreference(order.getBt360Preference());
        update(resourcePreference);
end

// vstype == 5 이면..
// Id : "RP_" + activity_id 매핑 또는 UUID 설정, [bt360ExpWorkerId]를 체크하여 값이 없을 경우 Resouce_Preference 생성 안함
// resource_id : [bt360ExpWorkerId] 매핑
// activity_id (or activity_Type_id or location_id) : [worktype] + [officeScode] + [workOdrNum ] 매핑
// preference : [bt360Preference] 매핑
rule "VS5_ResourcePreference"
	dialect "java"
	no-loop
	when
		order : WMWorkOrder()
		intglVo : IntglDataVo(vsType == ScenarioType.VS5)
		resourcePreference : ResourcePreference()
	then
		resourcePreference.setId(StringUtil.getUUID());
		resourcePreference.setResourceId(order.getBt360ExpWorkerId());
		resourcePreference.setActivityId(order.getWorkType() + order.getOfficeScode() + order.getWorkOdrNum());
		resourcePreference.setPreference(order.getBt360Preference());
        update(resourcePreference);
end

// vstype == 6 이면..
// Id : "RP_" + activity_id 매핑 또는 UUID 설정, [bt360ExpWorkerId]를 체크하여 값이 없을 경우 Resouce_Preference 생성 안함
// resource_id : [bt360ExpWorkerId] 매핑
// activity_id : [appointmentRequestId] 매핑
// preference : [bt360Preference] 매핑
rule "VS6_ResourcePreference"
	dialect "java"
	no-loop
	when
		order : WMAppointmentOrder()
		intglVo : IntglDataVo(vsType == ScenarioType.VS6)
		resourcePreference : ResourcePreference()
	then
		resourcePreference.setId(StringUtil.getUUID());
		resourcePreference.setResourceId(order.getBt360ExpWorkerId());
		resourcePreference.setActivityId(intglVo.getAppointmentRequestId());
		resourcePreference.setPreference(order.getBt360Preference());
        update(resourcePreference);
end

// vstype == 6C 이면..
// Id : "RP_" + activity_id 매핑 또는 UUID 설정, [bt360ExpWorkerId]를 체크하여 값이 없을 경우 Resouce_Preference 생성 안함.
// resource_id : [bt360ExpWorkerId] 매핑
// activity_id : [odrNum] 매핑
// preference : [bt360Preference] 매핑
rule "VS6C_ResourcePreference"
	dialect "java"
	no-loop
	when
		order : WMAppointmentOrder()
		intglVo : IntglDataVo(vsType == ScenarioType.VS6C)
		resourcePreference : ResourcePreference()
	then
		resourcePreference.setId(StringUtil.getUUID());
		resourcePreference.setResourceId(order.getBt360ExpWorkerId());
		resourcePreference.setActivityId(order.getOdrNum());
		resourcePreference.setPreference(order.getBt360Preference());
        update(resourcePreference);
end

// vstype == 10 이면..
// Id : "RP_" + activity_id 매핑 또는 UUID 설정 [bt360ExpWorkerId]를 체크하여 값이 없을 경우 Resouce_Preference 생성 안함.
// resource_id : [bt360ExpWorkerId] 매핑
// activity_id (or activity_Type_id or location_id) : [worktype] + [officeScode] + [workOdrNum ] 매핑
// preference : [bt360Preference] 매핑
rule "VS10_ResourcePreference"
	dialect "java"
	no-loop
	when
		order : WMWorkOrder()
		intglVo : IntglDataVo(vsType == ScenarioType.VS10)
		resourcePreference : ResourcePreference()
	then
		resourcePreference.setId(StringUtil.getUUID());
		resourcePreference.setResourceId(order.getBt360ExpWorkerId());
		resourcePreference.setActivityId(order.getWorkType() + order.getOfficeScode() + order.getWorkOdrNum());
		resourcePreference.setPreference(order.getBt360Preference());
        update(resourcePreference);
end
