//created on: 2012. 10. 15
package com.kt.oss.wmIntgl.datamapper.service.rules.mapper

import com.kt.oss.wmIntgl.common.constants.ScenarioType;
import com.kt.oss.wmIntgl.datahandler.domain.IntglDataVo;
import com._360scheduling.schema.dssystemdata.DsSystemData.SystemInput;

// vstype == 15A 이면
// id : Default 값으로 0 설정
// input_type : Default 값으로 'DATA' 설정
rule "VS15A_SystemInput"
	dialect "java"
	no-loop
	when
		intglVo : IntglDataVo(vsType == ScenarioType.VS15A)
		systemInput : SystemInput()
	then
		systemInput.setId("0");
		systemInput.setInputType("DATA");
        update(systemInput);
end

// vstype == 15D 이면
// id : Default 값으로 0 설정
// input_type : Default 값으로 'DATA' 설정
rule "VS15D_SystemInput"
	dialect "java"
	no-loop
	when
		intglVo : IntglDataVo(vsType == ScenarioType.VS15D)
		systemInput : SystemInput()
	then
		systemInput.setId("0");
		systemInput.setInputType("DATA");
        update(systemInput);
end
