//created on: 2012. 10. 15
package com.kt.oss.wmIntgl.datamapper.service.rules.mapper

import com.kt.oss.wmIntgl.common.constants.ScenarioType;
import com.kt.oss.wmIntgl.datahandler.domain.IntglDataVo;
import com.kt.oss.wmIntgl.datahandler.domain.WMResourceInfo;
import com._360scheduling.schema.dssystemdata.DsSystemData.UserGroup;

// vstype == 15D 이면..
// organisation_id : Default 값으로 1 설정
// user_id : [workerId] 매핑
// group_id : Default 값으로 'RFM' 설정
rule "VS15D_UserGroup"
	dialect "java"
	no-loop
	when
		order : WMResourceInfo()
		intglVo : IntglDataVo(vsType == ScenarioType.VS15D)
		userGroup : UserGroup()
	then
		userGroup.setOrganisationId("1");
		userGroup.setUserId(order.getWorkerId());
		userGroup.setGroupId("RFM");
        update(userGroup);
end
