//created on: 2012. 10. 15
package com.kt.oss.wmIntgl.datamapper.service.rules.mapper

import com.kt.oss.wmIntgl.common.constants.ScenarioType;
import com.kt.oss.wmIntgl.datahandler.domain.IntglDataVo;
import com.kt.oss.wmIntgl.datahandler.domain.WMResourceInfo;
import com._360scheduling.schema.dssystemdata.DsSystemData.UserExternalTask;

// vstype == 15D 이면..
// organisation_id : Default 값으로 1 설정
// user_id : [workerId] 매핑
// external_task_id : [sourceId] 매핑
rule "VS15D_UserExternalTask"
	dialect "java"
	no-loop
	when
		order : WMResourceInfo()
		intglVo : IntglDataVo(vsType == ScenarioType.VS15D)
		userExternalTask : UserExternalTask()
	then
		userExternalTask.setOrganisationId("1");
		userExternalTask.setUserId(order.getWorkerId());
		userExternalTask.setExternalTaskId(intglVo.getSourceId());
        update(userExternalTask);
end
