//created on: 2012. 10. 15
package com.kt.oss.wmIntgl.datamapper.service.rules.mapper

import com.kt.oss.wmIntgl.common.constants.ScenarioType;
import com.kt.oss.wmIntgl.common.utils.StringUtil;
import com._360scheduling.schema.dsscheduledata.DsScheduleData.AppointmentOffer;
import com.kt.oss.wmIntgl.datahandler.domain.IntglDataVo;
import com.kt.oss.wmIntgl.datamapper.service.rules.core.RulesDB;
import com.kt.oss.wmIntgl.datamapper.domain.intgl.WorkOrderStateVo;
import com.kt.oss.wmIntgl.datahandler.domain.WMAppointmentOffer;

// vstype == 6A 이면..
// appointmentRequestId : [appointment_request_id] 매핑
// offerId : [id] 매핑
// offerStartDt : [offer_start_datetime] 매핑
// offerEndDt : [offer_end_datetime] 매핑
// offerValue : [offer_value] 매핑
// available : [available] 매핑
// reasonType : [reason_type_id]를 조건으로 TB_WM_MAPPINGREASONTYPE 테이블을 정의하여  reasonType 설정
rule "VS6A_WMAppointmentOffer"
	dialect "java"
	no-loop
	when
		order : AppointmentOffer()
		intglVo : IntglDataVo(vsType == ScenarioType.VS6A)
		rulesDB : RulesDB()
		wmAppointmentOffer : WMAppointmentOffer()
	then
		wmAppointmentOffer.setAppointmentRequestId(order.getAppointmentRequestId());
		wmAppointmentOffer.setOfferId(order.getId());
		wmAppointmentOffer.setOfferStartDt(order.getOfferStartDatetime());
		wmAppointmentOffer.setOfferEndDt(order.getOfferEndDatetime());
		wmAppointmentOffer.setOfferValue(order.getOfferValue());
		wmAppointmentOffer.setAvailable(order.isAvailable());
		wmAppointmentOffer.setReasonType(rulesDB.selectReasonType(order.getReasonTypeId()));
        update(wmAppointmentOffer);
end
