//created on: 2012. 10. 15
package com.kt.oss.wmIntgl.datamapper.service.rules.mapper

import com.kt.oss.wmIntgl.common.constants.ScenarioType;
import com.kt.oss.wmIntgl.common.utils.StringUtil;
import com.kt.oss.wmIntgl.common.utils.ConversionUtil;
import com._360scheduling.schema.dsscheduledata.DsScheduleData.SuggestedDispatch;
import com.kt.oss.wmIntgl.datahandler.domain.IntglDataVo;
import com.kt.oss.wmIntgl.datamapper.service.rules.core.RulesDB;
import com.kt.oss.wmIntgl.datamapper.domain.intgl.WorkOrderStateVo;
import com.kt.oss.wmIntgl.datahandler.domain.WMWorkOrderResource;

// vstype == 2 이면..
// WorkType : substring( [activity_id], 1, 1) 매핑
// OfficeScode : substring( [activity_id], 2, 7) 매핑
// WorkOdrNum : substring( [activity_id], 8) 매핑
// odrNum : Default로 '' 설정
// Ttid : Default로 '' 설정
// WorkerID : [resource_id] 매핑
// WorkProgState :
// WorkProcState :
// BT360AddWorkProgState :
//  : [status_id]를 조건으로 TB_WM_MAPPINGSTATUS 테이블을 조회하여 매핑
//  : WorkProgState = status_cd, WorkProcState = complete_cd, bt360aDDWorkProgSate = additional_cd, where 절 조건 threesixtystatus_cd = [status_id]
// BT360WorkStartDT : [expected_start_datetime] 매핑
// BT360WorkEndDT : [expected_end_datetime] 매핑
// BT360FixedOdrYN : [fixed_resource] 매핑
// BT360FixedVisitDT : [date_time_fixed] 매핑
// BT360CommitValue : [commit_sort_value] 매핑
// BT360DatetimeStatus : [date_time_status] 매핑
// ILDateTimeStamp : [sourceDt] 매핑
// csctID : [sourceID] 매핑
// bt360PlanId : [plan_id] 매핑
rule "VS2_WMWorkOrderResource"
	dialect "java"
	no-loop
	when
		order : SuggestedDispatch()
		intglVo : IntglDataVo(vsType == ScenarioType.VS2)
		rulesDB : RulesDB()
		workOrderStateVo : WorkOrderStateVo()
		wmWorkOrderResource : WMWorkOrderResource()
	then
		workOrderStateVo = rulesDB.selectWMWorkOrderState(order.getStatusId());
		wmWorkOrderResource.setWorkType(StringUtil.leftstring(order.getActivityId(), 1));
		wmWorkOrderResource.setOfficeScode(StringUtil.substring(order.getActivityId(), 1, 7));
		wmWorkOrderResource.setWorkOdrNum(StringUtil.substring(order.getActivityId(), 7));
		wmWorkOrderResource.setOdrNum("");
		wmWorkOrderResource.setTtId("");
		wmWorkOrderResource.setWorkerId(order.getResourceId());
		wmWorkOrderResource.setWorkProgState(workOrderStateVo.getStatusCd());
		wmWorkOrderResource.setWorkProcState(workOrderStateVo.getCompleteCd());
		wmWorkOrderResource.setBt360AddWorkProgState(workOrderStateVo.getAdditionalCd());
		wmWorkOrderResource.setBt360WorkStartDt(order.getExpectedStartDatetime());
		wmWorkOrderResource.setBt360WorkEndDt(order.getExpectedEndDatetime());
		wmWorkOrderResource.setBt360FixedOdrYn(order.isFixedResource()? 1 : 0);
		wmWorkOrderResource.setBt360FixedVisitDt(order.getDateTimeFixed());
		wmWorkOrderResource.setBt360CommitValue(order.getCommitSortValue());
		wmWorkOrderResource.setBt360DatetimeStatus(order.getDateTimeStatus());
		wmWorkOrderResource.setIlDateTimeStamp(ConversionUtil.getXMLGregorianCalendar(intglVo.getSourceDt()));
		wmWorkOrderResource.setCsctID(intglVo.getSourceId());
		wmWorkOrderResource.setBt360PlanId(String.valueOf(order.getPlanId()));
        update(wmWorkOrderResource);
end
