//created on: 2012. 10. 15
package com.kt.oss.wmIntgl.datamapper.service.rules.mapper

import java.util.ArrayList;
import com.kt.oss.wmIntgl.datamapper.service.rules.core.Rules._Rules;

rule "intgl_rule_vs15d"
	dialect "java"
	no-loop
	when
		drlList : ArrayList()
	then
		drlList.add(_Rules.SystemInput);
		drlList.add(_Rules.SystemDataUpdate);
		drlList.add(_Rules.Users);
		drlList.add(_Rules.UserExternalTask);
		drlList.add(_Rules.UserGroup);
        update(drlList);
end
