//created on: 2012. 10. 15
package com.kt.oss.wmIntgl.datamapper.service.rules.mapper

import java.util.ArrayList;
import com.kt.oss.wmIntgl.datamapper.service.rules.core.Rules._Rules;

rule "intgl_rule_vs12"
	dialect "java"
	no-loop
	when
		drlList : ArrayList()
	then
		drlList.add(_Rules.SourceData);
		drlList.add(_Rules.SourceDataParameter);
		drlList.add(_Rules.InputReference);
        update(drlList);
end
